version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ai-chat-postgres
    environment:
      POSTGRES_DB: ai_chat_db
      POSTGRES_USER: ai_chat_user
      POSTGRES_PASSWORD: ai_chat_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ai_chat_user -d ai_chat_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: ai-chat-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://ai_chat_user:ai_chat_password@postgres:5432/ai_chat_db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: ai-chat-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data: 